### ISSUE TITLE
Make Citron a Swift package manager package?

### ISSUE THREAD

**Issue by dabrahams** [roop/citron#11]
I am currently referencing citron as a Git submodule of my project, but that creates problems for some of the less Git-experienced people on my team.  It would be much better if I could simply reference citron in my own `Package.swift`.

**Comment by dabrahams** [comment]
Another reason: I tried to define my own `Error` type and it broke `CitronParser.swift` which (reasonably) uses `Swift.Error` without qualification.  If it were in its own module I wouldn't have had that problem.

**Comment by roop** [comment]
I think CitronLexer and CitronParser can be spawned off into separate SPM modules, but I'm not quite sure what do with citron.c. I think it should be in an executable module, but I'm not sure how it can get used by the consuming project.

How do you envisage running the `citron` executable when using Citron through SPM? (Maybe you'll have a Makefile or Xcode run phase?) Does making citron.c part of an executable module help?

**Comment by dabrahams** [comment]
Because SPM doesn't support arbitrary build actions, right now I have a simple makefile that I use for my project:

```
# This Makefile is a thin layer on top of Swift package manager that handles the
# building of the citron parser generator binary and the generation of
# Sources/Parser.swift from Sources/Parser.citron.
GRAMMAR = ./Sources/Parser
CC = cc
SWIFTC = swiftc
BIN = ./bin
CITRON_SRC = ./citron/src
CITRON = ${BIN}/citron
SWIFT_FLAGS =
LCOV_FILE = ./.build/coverage.lcov
SHELL=/bin/bash

build: ${GRAMMAR}.swift
	swift build --enable-test-discovery ${SWIFT_FLAGS}

test: ${GRAMMAR}.swift
	swift test --enable-test-discovery ${SWIFT_FLAGS}

test-lcov: ${GRAMMAR}.swift
	swift build --build-tests --enable-code-coverage
	$$(swift test --enable-test-discovery --enable-code-coverage --verbose \
	   ${SWIFT_FLAGS} 2>&1 \
	   | tee /dev/tty | grep 'llvm-cov export' \
	   | sed -e 's/ export / export -format=lcov /') > "${LCOV_FILE}"

${CITRON}: ${CITRON_SRC}/citron.c
	mkdir -p ${BIN} && ${CC} $^ -o $@

clean:
	rm -rf ${GRAMMAR}.swift ./.build

${GRAMMAR}.swift: ${CITRON} ${GRAMMAR}.citron
	rm -f $@
	${CITRON} ${GRAMMAR}.citron -o $@
	chmod -w $@
```

**Comment by roop** [comment]
@dabrahams Can you please check if PR #13 (merged to master) suffices for your needs?

**Comment by dabrahams** [comment]
Good start; I got this warning when using it as a package though:

'citron' /Users/dabrahams/src/barcon/.build/checkouts/citron: warning: found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/dabrahams/src/barcon/.build/checkouts/citron/Sources/CitronParserModule/LICENSE.txt

**Comment by roop** [comment]
Sorry about that. Hopefully, commit 05da734 in master should fix that.
