### ISSUE TITLE
LICENSE file and "public domain code?"

### ISSUE THREAD

**Issue by dabrahams** [roop/citron#12]
Hi,

I have a much-improved lexer that I'd like to contribute to this project, but I'm having trouble interpreting the project's license, which looks like MIT, plus, in some files (that appear to be derived from Lemon), "public domain code".  My employer allows contribution to MIT licensed project, but not projects with public domain dedications.  It would be clarifying if you could add a LICENSE file for the entire project, even if individual files might have additional properties.

Thanks!

**Comment by roop** [comment]
If in trying to fix #11, we place the three files into three separate modules, then we can have a separate LICENSE for each module. CitronLexer's LICENSE file will be just MIT. Do you think that would suffice for you to contribute to the lexer?

**Comment by dabrahams** [comment]
Yes, I think so!

**Comment by dabrahams** [comment]
FYI: as I'm changing jobs very shortly, my ability to contribute this code back is going to evaporate soon.  No pressure ;-)

**Comment by roop** [comment]
Sorry about the delay. I'll get this done the coming weekend.

**Comment by roop** [comment]
Decided to work on it today after all :). Fixed in PR #14.
